version: '3.9'

services:
  app:
    container_name: docker_bootcamp
    build: .
    ports:
      - '8020:8000'
    volumes:
      - .:/home/app
    networks:
      - common-network

  # minio:
  #   container_name: minio
  #   image: minio/minio
  #   ports:
  #     - '9000:9000'
  #     - '9001:9001'
  #   volumes:
  #     - 'minio:/data'
  #   environment:
  #     - MINIO_ROOT_USER=minio
  #     - MINIO_ROOT_PASSWORD=miniominio
  #   restart: always
  #   platform: linux/x86_64
  #   command: server /data --console-address ":9001"

volumes:
  app:
#   minio:
networks:
  common-network:
    driver: bridge
